install.packages("data.table")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("readr")
install.packages("Matrix")
install.packages("caret")
install.packages("data.table")
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
install.packages("devtools", repos = "http://cran.rstudio.com") 